### ISSUE TITLE
Displaying N running jobs does not work correctly.

### ISSUE THREAD

**Issue by Paulie14** [GeoMop/MLMC#92]
When running on Charon, the script always displays "N running 1000", where 1000 is my sample count.
I suppose it looks for presence of pbs ID file (`permanent_jobID_xxxx`), but these are still kept even when the calculation of a sample is finished.
I do not think that I influenced this functionality at all.
Can it be checked on a simple problem?

**Comment by martinspetlik** [comment]
The only occurrences of "N running: ..." I found are in `mlmc.test.01_cond_field.process_simple.all_collect()` and in `src.mlmc.tool.process_base.all_collect()`. It should show number of running (scheduled or running) samples.
If the job is finished the file JobId_PbsId (e.g. 0000_3635405) is deleted, otherwise job is considered running and scheduled samples from these jobs are included into "N running: ...".

You can see for yourself in `src.mlmc.sampling_pool_pbs._get_result_files()`

**Comment by Paulie14** [comment]
PE revelation: N running is connected to number of running JOBS not SAMPLES.
It works ok.
